### ISSUE TITLE
Сделать возможность вносить свои слова в словарь

### ISSUE THREAD

**Issue by EgorBanin** [diodincova/dictionary#7]
Доработать  init.php сделав его интерактивным:
1. запускаем из консоли `php init.php`, скрипт выводит: "Введите слово".
2. вводим слово, жмём энтер, скрипт проверяет есть ли слово в словаре. Если есть, то сообщает "Слово уже есть в словаре" и снова предлагает 1. "Ведите слово".
3. Если слова в словаре нет, то скрипт по очереди запрашивает translation, transcription, description, examples. Когда всё введено, скрипт сохраняет новое слово в файл и снова 1. "Введите слово".
Выход из скрипта по ctrl+c. Если пользователь выходит в процессе заполнения, то слово не сохраняется.

**Comment by EgorBanin** [comment]
Чтобы прочитать пользовательский ввод, можно воспользоваться функцией [readline](https://www.php.net/manual/ru/function.readline.php).

**Comment by diodincova** [comment]
done
